"""Public API for Agent Regression Kit."""

from .version import __version__

from .adapters import (
    AgentAdapter,
    AsyncAgentAdapter,
    AsyncCallableAgentAdapter,
    AsyncRunContext,
    AsyncScriptedAgentAdapter,
    CallableAgentAdapter,
    RunContext,
    ScriptedAgentAdapter,
    ScriptedSessionAdapter,
)
from .async_record import AsyncToolExecutor, async_record_run, record_async_run
from .batch import compare_trace_batch
from .benchmark import decide_benchmark, prepare_benchmark, score_benchmark
from .performance import evaluate_performance_gate, run_performance_benchmark
from .readiness import (
    FINAL_PROFILE,
    FINAL_THRESHOLDS,
    READINESS_SCHEMA_VERSION,
    evaluate_readiness,
)
from .cassette import CassetteEntry, CassetteToolExecutor, ReplayMismatchError, replay_agent_run
from .batch_record import ScenarioBatchResult, ScenarioCase, ScenarioResult, record_scenario_batch
from .compare import ComparisonPolicy, compare_traces
from .coverage import (
    compare_trace_coverage,
    trace_business_branch,
    trace_outcome_path,
    trace_tool_path,
)
from .isolation import SnapshotBackend, StateIsolation
from .compat import run_compatibility_smoke
from .contracts import ContractPolicy
from .history import HistoryPoint, HistoryReport, build_history_report
from .framework import FrameworkTraceRecorder, record_framework_run
from .framework_integrations import (
    trace_from_langgraph_result,
    trace_from_openai_agents_result,
    trace_from_pydantic_ai_result,
)
from .deepseek import DeepSeekAPIError, record_deepseek_tool_run
from .agentdojo import evaluate_agentdojo_run, trace_from_agentdojo_run
from .mcp import (
    McpProtocolError,
    McpEventStream,
    McpToolExecutor,
    McpTimeoutError,
    McpTransportError,
    StdioMcpClient,
    StreamableHttpMcpClient,
    record_mcp_http_run,
    record_mcp_run,
)
from .model import AgentTrace, TraceValidationError
from .record import (
    FixtureTools,
    ToolExecutionResult,
    ToolExecutor,
    WorldStateProvider,
    isolated_record_run,
    isolated_record_session,
    record_run,
    record_session,
)
from .redaction import DEFAULT_REDACTION_POLICY, RedactionPolicy
from .replay import replay_trace
from .reports import (
    render_batch_junit,
    render_batch_markdown,
    render_coverage_junit,
    render_coverage_markdown,
    render_async_markdown,
    render_history_junit,
    render_history_markdown,
    render_junit,
    render_markdown,
    render_scenario_batch_junit,
    render_scenario_batch_markdown,
    render_stability_junit,
    render_stability_markdown,
    render_session_junit,
    render_session_markdown,
    render_report_index_markdown,
    render_sampling_study_markdown,
    render_readiness_markdown,
)
from .report_index import build_report_index
from .scenario import StatefulFixtureTools, WorldState
from .session import AgentSession, check_session_state_continuity, compare_sessions
from .stability import (
    RECOMMENDED_STABILITY_RUNS,
    StabilityPolicy,
    StabilityReport,
    StabilityRun,
    evaluate_stability,
    record_stability,
)
from .statistics import wilson_interval
from .study import (
    STUDY_SCHEMA_VERSION,
    SamplingProvenance,
    SamplingStudyReport,
    canonical_sha256,
    evaluate_sampling_study,
    sha256_file,
)
from .sdk import AdapterSpec
from .adapter_contract import check_adapter_contract, check_async_adapter_contract
from .public_api import (
    LEGACY_PUBLIC_API_VERSIONS,
    PUBLIC_API_VERSION,
    SUPPORTED_CONTRACT_SCHEMA_VERSIONS,
    SUPPORTED_REPORT_SCHEMA_VERSIONS,
    SUPPORTED_SESSION_SCHEMA_VERSIONS,
    SUPPORTED_TRACE_SCHEMA_VERSIONS,
    public_api_manifest,
)
from .migration import (
    build_compatibility_report,
    build_trace_migration_report,
    check_document_compatibility,
    check_public_api_version,
    migrate_trace,
)
from .templates import initialize_adapter_template
from .tau2 import (
    TAU2_AIRLINE_OBSERVATION_TOOLS,
    TAU2_AIRLINE_WRITE_TOOLS,
    TAU2_RETAIL_OBSERVATION_TOOLS,
    TAU2_RETAIL_WRITE_TOOLS,
    TAU2_TELECOM_OBSERVATION_TOOLS,
    TAU2_TELECOM_WRITE_TOOLS,
    build_tau2_airline_contract,
    build_tau2_retail_contract,
    build_tau2_telecom_contract,
    evaluate_tau2_airline_results,
    evaluate_tau2_retail_results,
    evaluate_tau2_telecom_results,
    split_tau2_payload_by_task,
    trace_from_tau2_simulation,
)
from .workspace import build_workspace_manifest
from .rule_agent import (
    NORMAL,
    PARAMETER_REGRESSION,
    RESULT_MISREAD,
    RuleBasedOrderAgentAdapter,
)

__all__ = [
    "AgentAdapter",
    "AsyncAgentAdapter",
    "AsyncCallableAgentAdapter",
    "AsyncRunContext",
    "AsyncScriptedAgentAdapter",
    "AsyncToolExecutor",
    "async_record_run",
    "record_async_run",
    "CallableAgentAdapter",
    "AgentTrace",
    "CassetteEntry",
    "CassetteToolExecutor",
    "AgentSession",
    "compare_trace_batch",
    "prepare_benchmark",
    "decide_benchmark",
    "score_benchmark",
    "run_performance_benchmark",
    "evaluate_performance_gate",
    "FINAL_PROFILE",
    "FINAL_THRESHOLDS",
    "READINESS_SCHEMA_VERSION",
    "evaluate_readiness",
    "record_scenario_batch",
    "ScenarioBatchResult",
    "ScenarioCase",
    "ScenarioResult",
    "compare_trace_coverage",
    "ComparisonPolicy",
    "ContractPolicy",
    "DEFAULT_REDACTION_POLICY",
    "FixtureTools",
    "FrameworkTraceRecorder",
    "trace_from_langgraph_result",
    "trace_from_openai_agents_result",
    "trace_from_pydantic_ai_result",
    "DeepSeekAPIError",
    "record_deepseek_tool_run",
    "McpProtocolError",
    "McpEventStream",
    "McpToolExecutor",
    "McpTimeoutError",
    "McpTransportError",
    "NORMAL",
    "PARAMETER_REGRESSION",
    "RedactionPolicy",
    "RESULT_MISREAD",
    "RunContext",
    "RuleBasedOrderAgentAdapter",
    "ScriptedAgentAdapter",
    "ScriptedSessionAdapter",
    "StatefulFixtureTools",
    "StateIsolation",
    "SnapshotBackend",
    "StdioMcpClient",
    "StreamableHttpMcpClient",
    "TraceValidationError",
    "ToolExecutionResult",
    "ToolExecutor",
    "trace_tool_path",
    "trace_outcome_path",
    "trace_business_branch",
    "WorldStateProvider",
    "WorldState",
    "compare_traces",
    "compare_sessions",
    "check_session_state_continuity",
    "StabilityPolicy",
    "RECOMMENDED_STABILITY_RUNS",
    "StabilityReport",
    "StabilityRun",
    "evaluate_stability",
    "record_stability",
    "wilson_interval",
    "STUDY_SCHEMA_VERSION",
    "SamplingProvenance",
    "SamplingStudyReport",
    "canonical_sha256",
    "evaluate_sampling_study",
    "sha256_file",
    "AdapterSpec",
    "check_adapter_contract",
    "check_async_adapter_contract",
    "PUBLIC_API_VERSION",
    "LEGACY_PUBLIC_API_VERSIONS",
    "SUPPORTED_CONTRACT_SCHEMA_VERSIONS",
    "SUPPORTED_REPORT_SCHEMA_VERSIONS",
    "SUPPORTED_SESSION_SCHEMA_VERSIONS",
    "SUPPORTED_TRACE_SCHEMA_VERSIONS",
    "public_api_manifest",
    "build_compatibility_report",
    "build_trace_migration_report",
    "check_document_compatibility",
    "check_public_api_version",
    "migrate_trace",
    "initialize_adapter_template",
    "TAU2_RETAIL_OBSERVATION_TOOLS",
    "TAU2_RETAIL_WRITE_TOOLS",
    "TAU2_AIRLINE_OBSERVATION_TOOLS",
    "TAU2_AIRLINE_WRITE_TOOLS",
    "TAU2_TELECOM_OBSERVATION_TOOLS",
    "TAU2_TELECOM_WRITE_TOOLS",
    "build_tau2_airline_contract",
    "build_tau2_retail_contract",
    "build_tau2_telecom_contract",
    "evaluate_tau2_airline_results",
    "evaluate_tau2_retail_results",
    "evaluate_tau2_telecom_results",
    "split_tau2_payload_by_task",
    "trace_from_tau2_simulation",
    "HistoryPoint",
    "HistoryReport",
    "build_history_report",
    "build_report_index",
    "build_workspace_manifest",
    "run_compatibility_smoke",
    "record_run",
    "record_framework_run",
    "ReplayMismatchError",
    "replay_agent_run",
    "record_session",
    "isolated_record_run",
    "isolated_record_session",
    "record_mcp_run",
    "record_mcp_http_run",
    "replay_trace",
    "render_junit",
    "render_markdown",
    "render_batch_junit",
    "render_batch_markdown",
    "render_async_markdown",
    "render_history_junit",
    "render_history_markdown",
    "render_scenario_batch_junit",
    "render_scenario_batch_markdown",
    "render_stability_junit",
    "render_stability_markdown",
    "render_sampling_study_markdown",
    "render_readiness_markdown",
    "render_coverage_junit",
    "render_coverage_markdown",
    "render_session_junit",
    "render_session_markdown",
    "render_report_index_markdown",
    "__version__",
]
