from __future__ import annotations

import argparse
import json
import shlex
import sys
from pathlib import Path
from typing import Any, Dict

from .adapters import ScriptedAgentAdapter
from .batch import compare_trace_batch
from .compare import ComparisonPolicy, compare_traces
from .compat import run_compatibility_smoke
from .config import load_compare_config
from .model import AgentTrace, TraceValidationError
from .mcp import (
    McpTransportError,
    StdioMcpClient,
    StreamableHttpMcpClient,
    record_mcp_http_run,
    record_mcp_run,
)
from .record import FixtureTools, record_run
from .redaction import DEFAULT_REDACTION_POLICY, RedactionPolicy
from .reports import render_batch_junit, render_batch_markdown, render_junit, render_markdown
from .replay import replay_trace
from .scaffold import initialize_project


VERSION = "1.7.0"


def _read_json(path: str) -> Dict[str, Any]:
    with Path(path).open(encoding="utf-8") as handle:
        value = json.load(handle)
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _write_output(value: Dict[str, Any], out: str | None = None) -> None:
    safe_value = DEFAULT_REDACTION_POLICY.redact(value)
    rendered = json.dumps(safe_value, ensure_ascii=False, indent=2) + "\n"
    if out:
        output_path = Path(out)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(rendered, encoding="utf-8")
    print(rendered, end="")


def _write_text(value: str, out: str | None = None) -> None:
    if out:
        output_path = Path(out)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(value, encoding="utf-8")
    print(value, end="")


def _parse_headers(values: list[str]) -> Dict[str, str]:
    headers: Dict[str, str] = {}
    for value in values:
        name, separator, header_value = value.partition(":")
        if not separator or not name.strip():
            raise ValueError(f"header must use 'Name: value' syntax: {value!r}")
        headers[name.strip()] = header_value.strip()
    return headers


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="agent-regression")
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init = subparsers.add_parser(
        "init", help="scaffold an Agent Regression Kit integration in a project"
    )
    init.add_argument(
        "--directory",
        default=".",
        help="project directory to scaffold (default: current directory)",
    )
    init.add_argument(
        "--force",
        action="store_true",
        help="overwrite files generated by a previous init",
    )

    record = subparsers.add_parser("record", help="record a deterministic scenario")
    record.add_argument("--scenario", required=True)
    record.add_argument("--out", required=True)
    record.add_argument(
        "--secret-value", action="append", default=[], help="literal secret value to redact; repeatable"
    )

    mcp_record = subparsers.add_parser(
        "mcp-record", help="record a scenario through an MCP stdio server"
    )
    mcp_record.add_argument("--scenario", required=True)
    mcp_record.add_argument("--out", required=True)
    mcp_record.add_argument(
        "--server-command",
        help="shell-style command string; defaults to the project-owned fixture",
    )
    mcp_record.add_argument("--timeout", type=float, default=5.0)
    mcp_record.add_argument(
        "--secret-value", action="append", default=[], help="literal secret value to redact; repeatable"
    )

    mcp_http_record = subparsers.add_parser(
        "mcp-http-record", help="record a scenario through an MCP Streamable HTTP server"
    )
    mcp_http_record.add_argument("--scenario", required=True)
    mcp_http_record.add_argument("--url", required=True)
    mcp_http_record.add_argument("--out", required=True)
    mcp_http_record.add_argument("--timeout", type=float, default=5.0)
    mcp_http_record.add_argument(
        "--header",
        action="append",
        default=[],
        help="HTTP request header in 'Name: value' form; repeatable",
    )
    mcp_http_record.add_argument(
        "--secret-value", action="append", default=[], help="literal secret value to redact; repeatable"
    )

    smoke = subparsers.add_parser(
        "mcp-smoke", help="run non-mutating compatibility checks against an MCP server"
    )
    smoke_transport = smoke.add_mutually_exclusive_group(required=True)
    smoke_transport.add_argument(
        "--server-command", help="shell-style command for an MCP stdio server"
    )
    smoke_transport.add_argument("--url", help="MCP Streamable HTTP endpoint")
    smoke.add_argument(
        "--stdio-framing",
        choices=["newline", "content-length"],
        default="newline",
        help="stdio framing for --server-command (default: newline)",
    )
    smoke.add_argument("--timeout", type=float, default=5.0)
    smoke.add_argument(
        "--header",
        action="append",
        default=[],
        help="HTTP request header in 'Name: value' form; repeatable",
    )
    smoke.add_argument("--out")

    replay = subparsers.add_parser("replay", help="validate and inspect recorded evidence")
    replay.add_argument("--trace", required=True)
    replay.add_argument("--out")

    validate = subparsers.add_parser("validate", help="validate an AgentTrace document")
    validate.add_argument("--trace", required=True)

    compare = subparsers.add_parser("compare", help="compare candidate evidence to a baseline")
    compare.add_argument("--baseline")
    compare.add_argument("--candidate")
    compare.add_argument("--config", help="JSON config with project-level compare defaults")
    compare.add_argument("--out")
    compare.add_argument("--format", choices=["json", "junit", "markdown"])
    compare.add_argument(
        "--final-answer-mode",
        choices=["exact", "claims-only"],
        default=None,
        help="compare final prose exactly or compare only structured claims",
    )
    compare.add_argument(
        "--secret-value", action="append", default=None, help="literal secret value to redact; repeatable"
    )
    compare.add_argument(
        "--allow-category",
        action="append",
        default=None,
        help="difference category that should not fail the comparison; repeatable",
    )

    baseline = subparsers.add_parser("baseline", help="manage validated baseline traces")
    baseline_actions = baseline.add_subparsers(dest="baseline_action", required=True)
    accept = baseline_actions.add_parser("accept", help="validate and store a baseline trace")
    accept.add_argument("--trace", required=True)
    accept.add_argument("--out", required=True)
    show = baseline_actions.add_parser("show", help="validate and summarize a baseline trace")
    show.add_argument("--baseline", required=True)
    compare.add_argument(
        "--allow-path",
        action="append",
        default=None,
        help="exact difference path that should not fail the comparison; repeatable",
    )

    batch_compare = subparsers.add_parser(
        "batch-compare", help="compare matching Trace files across two directories"
    )
    batch_compare.add_argument("--baseline-dir", required=True)
    batch_compare.add_argument("--candidate-dir", required=True)
    batch_compare.add_argument("--out")
    batch_compare.add_argument("--format", choices=["json", "junit", "markdown"], default="json")
    batch_compare.add_argument(
        "--final-answer-mode",
        choices=["exact", "claims-only"],
        default="exact",
    )
    batch_compare.add_argument("--secret-value", action="append", default=[])
    batch_compare.add_argument("--allow-category", action="append", default=[])
    batch_compare.add_argument("--allow-path", action="append", default=[])
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    redaction_policy = RedactionPolicy(
        secret_values=tuple(getattr(args, "secret_value", None) or [])
    )
    try:
        compare_config = (
            load_compare_config(args.config)
            if args.command == "compare" and args.config
            else {}
        )
        if args.command == "compare" and args.secret_value is None:
            redaction_policy = RedactionPolicy(
                secret_values=tuple(compare_config.get("secret_values", []))
            )
        if args.command == "init":
            root = Path(args.directory).resolve()
            root.mkdir(parents=True, exist_ok=True)
            result = initialize_project(root, force=args.force)
            _write_output({"ok": True, "directory": str(root), **result})
            return 0

        if args.command == "batch-compare":
            report = compare_trace_batch(
                args.baseline_dir,
                args.candidate_dir,
                policy=ComparisonPolicy(
                    allowed_categories=set(args.allow_category),
                    allowed_paths=set(args.allow_path),
                    final_answer_mode=args.final_answer_mode,
                ),
                redaction_policy=redaction_policy,
            )
            if args.format == "junit":
                _write_text(render_batch_junit(report), args.out)
            elif args.format == "markdown":
                _write_text(render_batch_markdown(report), args.out)
            else:
                _write_output(report, args.out)
            return 0 if report["passed"] else 1

        if args.command in {"record", "mcp-record", "mcp-http-record"}:
            scenario = _read_json(args.scenario)
            adapter = ScriptedAgentAdapter(scenario["agent"], scenario["plan"])
            if args.command == "record":
                trace = record_run(
                    adapter,
                    scenario.get("input"),
                    FixtureTools(scenario.get("tools", {})),
                    run_id=scenario["run_id"],
                    metadata=scenario.get("metadata"),
                    redaction_policy=redaction_policy,
                )
            elif args.command == "mcp-record":
                command = (
                    shlex.split(args.server_command)
                    if args.server_command
                    else [sys.executable, "-m", "agent_regression.fixtures.mcp_stdio_server"]
                )
                trace = record_mcp_run(
                    adapter,
                    scenario.get("input"),
                    command,
                    run_id=scenario["run_id"],
                    metadata=scenario.get("metadata"),
                    timeout_seconds=args.timeout,
                    redaction_policy=redaction_policy,
                )
            else:
                trace = record_mcp_http_run(
                    adapter,
                    scenario.get("input"),
                    args.url,
                    run_id=scenario["run_id"],
                    metadata=scenario.get("metadata"),
                    timeout_seconds=args.timeout,
                    headers=_parse_headers(args.header),
                    redaction_policy=redaction_policy,
                )
            _write_output(trace.to_dict(), args.out)
            return 0

        if args.command == "replay":
            report = replay_trace(AgentTrace.from_dict(_read_json(args.trace)))
            _write_output(report, args.out)
            return 0

        if args.command == "mcp-smoke":
            if args.url:
                client = StreamableHttpMcpClient(
                    args.url,
                    timeout_seconds=args.timeout,
                    headers=_parse_headers(args.header),
                )
            else:
                client = StdioMcpClient(
                    shlex.split(args.server_command),
                    timeout_seconds=args.timeout,
                    framing=args.stdio_framing,
                )
            with client:
                _write_output(run_compatibility_smoke(client), args.out)
            return 0

        if args.command == "validate":
            trace = AgentTrace.from_dict(_read_json(args.trace))
            _write_output(
                {
                    "ok": True,
                    "schema_version": trace.schema_version,
                    "run_id": trace.run_id,
                    "event_count": len(trace.events),
                }
            )
            return 0

        if args.command == "baseline":
            if args.baseline_action == "accept":
                trace = AgentTrace.from_dict(_read_json(args.trace))
                _write_output(trace.to_dict(), args.out)
                return 0
            trace = AgentTrace.from_dict(_read_json(args.baseline))
            report = replay_trace(trace)
            _write_output(
                {
                    "ok": True,
                    "run_id": trace.run_id,
                    "agent": trace.agent,
                    "event_count": len(trace.events),
                    "tool_call_count": len(report["calls"]),
                }
            )
            return 0

        baseline_path = args.baseline or compare_config.get("baseline")
        candidate_path = args.candidate or compare_config.get("candidate")
        if not baseline_path or not candidate_path:
            raise ValueError("compare requires --baseline and --candidate, or --config with both")
        output_format = args.format or compare_config.get("format", "json")
        final_answer_mode = args.final_answer_mode or compare_config.get("final_answer_mode", "exact")
        allowed_categories = (
            set(args.allow_category)
            if args.allow_category is not None
            else set(compare_config.get("allow_categories", []))
        )
        allowed_paths = (
            set(args.allow_path)
            if args.allow_path is not None
            else set(compare_config.get("allow_paths", []))
        )
        output_path = args.out or compare_config.get("report")
        baseline = AgentTrace.from_dict(_read_json(baseline_path))
        candidate = AgentTrace.from_dict(_read_json(candidate_path))
        report = compare_traces(
            baseline,
            candidate,
            ComparisonPolicy(
                allowed_categories=allowed_categories,
                allowed_paths=allowed_paths,
                final_answer_mode=final_answer_mode,
            ),
            redaction_policy,
        )
        if output_format == "junit":
            _write_text(render_junit(report), output_path)
        elif output_format == "markdown":
            _write_text(render_markdown(report), output_path)
        else:
            _write_output(report, output_path)
        return 0 if report["passed"] else 1
    except (KeyError, ValueError, TraceValidationError, McpTransportError) as exc:
        _write_output({"ok": False, "error": redaction_policy.redact(str(exc))})
        return 2


if __name__ == "__main__":
    sys.exit(main())
