"""Project scaffolding for first-time Agent Regression Kit users."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Dict, List

from .mcp import record_mcp_run
from .version import __version__


class _ScaffoldAgent:
    """The deterministic Agent used to seed a first-use baseline."""

    identity = {"name": "my-agent", "version": "0.1.0"}

    def run(self, request, context):
        order_id = str(request).rsplit(" ", 1)[-1]
        order = context.call_tool("get_order", {"order_id": order_id})
        context.final_answer(
            f"Order {order_id} status: {order['status']}",
            {"order_id": order_id, "order_status": order["status"]},
        )


_FILES: Dict[str, str] = {
    ".agent-regression/config.json": json.dumps(
        {
            "baseline": "baselines/my-agent.trace.json",
            "candidate": "work/my-agent.trace.json",
            "report": "outputs/my-agent.compare.md",
            "format": "markdown",
            "final_answer_mode": "claims-only",
            "contract": {
                "required_claims": [
                    "final_answer.claims.order_id",
                    "final_answer.claims.order_status",
                ],
                "assertions": [
                    {
                        "path": "final_answer.claims.order_status",
                        "equals": "not_shipped",
                    }
                ],
                "must_call": [
                    {
                        "tool": "get_order",
                        "arguments": {"order_id": "123"},
                    }
                ],
                "must_not_call": ["delete_order", "refund_order"],
                "max_steps": 1,
            },
        },
        indent=2,
    )
    + "\n",
    "AGENT_REGRESSION.md": """# Agent Regression Kit starter project

This folder is generated by `agent-regression init`. It contains a deterministic
starter baseline, a candidate trace, a strict Contract and a GitHub Actions
workflow. The starter baseline is a fixture artifact, not a business approval;
inspect it and explicitly accept a real Agent baseline after you replace the
example Agent.

## First run

```bash
python scripts/record_agent.py --variant normal --out work/my-agent.trace.json
agent-regression check --config .agent-regression/config.json
agent-regression compare --config .agent-regression/config.json
```

The normal run exits with `0`. To see a real, intentional regression:

```bash
python scripts/record_agent.py --variant wrong-resource --out work/my-agent.trace.json
agent-regression compare --config .agent-regression/config.json
# expected exit code: 1
```

Other built-in defects are `skip-tool` and `misread-result`. Replace the
example Agent and keep the same boundary: tool calls go through
`context.call_tool`, and business conclusions are emitted as `claims`.

## Files

- `baselines/`: reviewed evidence; the generated file is only a starter fixture until you review its business meaning.
- `work/`: generated candidate evidence; do not commit it.
- `outputs/`: JSON/Markdown/JUnit reports; upload them as CI artifacts.
- `.agent-regression/config.json`: paths plus the Contract that blocks unsafe changes.
- `scripts/record_agent.py`: replace `ExampleAgent` with your real Agent adapter.

中文说明：这个模板先用一个本地确定性 MCP Fixture 跑通“正常通过”和“故意失败”，
不需要模型 Key。接入真实 Agent 时，保留 `context.call_tool` 和结构化 `claims`，
然后把自己的 Agent 运行脚本放进 CI。
""",
    ".gitignore": """work/\noutputs/\n.venv/\n__pycache__/\n""",
    "baselines/README.md": """# Baselines

Commit reviewed AgentTrace files here. A baseline is the expected behavior
against which pull-request candidate traces are compared. Update it explicitly
after reviewing a deliberate behavior change; CI never overwrites it.

The generated starter file is `my-agent.trace.json`. It is useful for proving
the template works, but it is not an approved business baseline. Replace the
example Agent, review the resulting Trace, then accept the real baseline
explicitly. Keep its business meaning stable even if run-scoped IDs or
transport metadata change.
""",
    "scripts/record_agent.py": '''"""Generate a candidate AgentTrace for CI.

Replace ExampleAgent.run with your Agent integration. Keep tool calls routed
through context.call_tool and finish through context.final_answer.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from agent_regression import record_mcp_run


class ExampleAgent:
    identity = {"name": "my-agent", "version": "0.1.0"}

    def __init__(self, variant):
        self.variant = variant

    def run(self, request, context):
        order_id = str(request).rsplit(" ", 1)[-1]
        if self.variant == "skip-tool":
            context.final_answer(
                f"Order {order_id} status: not_shipped",
                {"order_id": order_id, "order_status": "not_shipped"},
            )
            return
        query_id = "999" if self.variant == "wrong-resource" else order_id
        order = context.call_tool("get_order", {"order_id": query_id})
        status = order["status"]
        if self.variant == "misread-result" and status == "not_shipped":
            status = "shipped"
        context.final_answer(
            f"Order {query_id} status: {status}",
            {"order_id": query_id, "order_status": status},
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="work/my-agent.trace.json")
    parser.add_argument(
        "--variant",
        choices=["normal", "wrong-resource", "skip-tool", "misread-result"],
        default="normal",
        help="normal passes; the other variants are intentional regression demos",
    )
    args = parser.parse_args()
    trace = record_mcp_run(
        ExampleAgent(args.variant),
        "lookup order 123",
        [sys.executable, "-m", "agent_regression.fixtures.mcp_stdio_server"],
        run_id="my-agent-123",
    )
    destination = Path(args.out)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(trace.to_dict(), ensure_ascii=False, indent=2) + "\\n",
        encoding="utf-8",
    )
    print(destination)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
''',
    ".github/workflows/agent-regression.yml": '''name: agent-regression

on:
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Agent Regression Kit
        run: python -m pip install "git+https://github.com/ANTAO94/agent-regression-kit.git@__AGENT_REGRESSION_REF__"
      - name: Record candidate trace
        run: python scripts/record_agent.py --out work/my-agent.trace.json
      - name: Preflight config and Trace inputs
        run: agent-regression check --config .agent-regression/config.json --kind single
      - name: Compare with reviewed baseline
        uses: ANTAO94/agent-regression-kit/.github/actions/agent-regression@__AGENT_REGRESSION_REF__
        with:
          baseline: baselines/my-agent.trace.json
          candidate: work/my-agent.trace.json
          report: outputs/my-agent.junit.xml
          json-report: outputs/my-agent.compare.json
      - name: Build report index
        if: always()
        uses: ANTAO94/agent-regression-kit/.github/actions/agent-report-index@__AGENT_REGRESSION_REF__
        with:
          report-dir: outputs
          fail-on-regression: 'true'
      - name: Upload regression report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-regression-report
          path: outputs/
''',
    ".github/workflows/agent-coverage.yml": '''name: agent-scenario-coverage

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Agent Regression Kit
        run: python -m pip install "git+https://github.com/ANTAO94/agent-regression-kit.git@__AGENT_REGRESSION_REF__"
      - name: Record scenario traces
        run: python scripts/record_agent.py --out work/scenarios/order.trace.json
      - name: Check expected Agent paths
        uses: ANTAO94/agent-regression-kit/.github/actions/agent-coverage@__AGENT_REGRESSION_REF__
        with:
          trace-dir: work/scenarios
          expected-paths: get_order
          json-report: outputs/agent-coverage.json
      - name: Build report index
        if: always()
        uses: ANTAO94/agent-regression-kit/.github/actions/agent-report-index@__AGENT_REGRESSION_REF__
        with:
          report-dir: outputs
          fail-on-regression: 'true'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: agent-coverage-report
          path: outputs/
''',
}


def initialize_project(root: Path, *, force: bool = False) -> Dict[str, List[str]]:
    """Create a first-use project layout without overwriting by default."""
    created: List[str] = []
    skipped: List[str] = []
    for relative, content in _FILES.items():
        destination = root / relative
        if destination.exists() and not force:
            skipped.append(relative)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(
            content.replace("__AGENT_REGRESSION_REF__", __version__),
            encoding="utf-8",
        )
        created.append(relative)
    baseline_path = root / "baselines/my-agent.trace.json"
    candidate_path = root / "work/my-agent.trace.json"
    if force or not baseline_path.exists():
        trace = record_mcp_run(
            _ScaffoldAgent(),
            "lookup order 123",
            [sys.executable, "-m", "agent_regression.fixtures.mcp_stdio_server"],
            run_id="my-agent-123",
        )
        rendered = json.dumps(trace.to_dict(), ensure_ascii=False, indent=2) + "\n"
        baseline_path.parent.mkdir(parents=True, exist_ok=True)
        baseline_path.write_text(rendered, encoding="utf-8")
        created.append("baselines/my-agent.trace.json")
        candidate_path.parent.mkdir(parents=True, exist_ok=True)
        candidate_path.write_text(rendered, encoding="utf-8")
        created.append("work/my-agent.trace.json")
    return {"created": created, "skipped": skipped}
